### ISSUE TITLE
Instructions `make dev ` fails

### ISSUE THREAD

**Issue by seamus-oconnor** [sandstorm-io/sandstorm-rawapi-example#1]
I cloned the repo and followed the instructions in the Readme. Running `make dev` gives this error:

```
$ make dev
capnp compile --src-prefix=/opt/sandstorm/latest/usr/include -oc++:tmp /opt/sandstorm/latest/usr/include/sandstorm/*.capnp
/opt/sandstorm/latest/usr/include/sandstorm/grain.capnp:179:37-47: error: Not defined: Capability
/opt/sandstorm/latest/usr/include/sandstorm/grain.capnp:159:17-27: error: Not defined: Capability
/opt/sandstorm/latest/usr/include/sandstorm/grain.capnp:620:47-57: error: Not defined: Capability
/opt/sandstorm/latest/usr/include/sandstorm/supervisor.capnp:69:37-47: error: Not defined: Capability
/opt/sandstorm/latest/usr/include/sandstorm/supervisor.capnp:98:36-67: error: Too many generic parameters.
Makefile:18: recipe for target 'tmp/genfiles' failed
make: *** [tmp/genfiles] Error 1
```

**Comment by kentonv** [comment]
Hi Séamus,

Hmm, the problem here is that Sandstorm and Cap'n Proto are developed together, and as a result Sandstorm tends to use unreleased features of Cap'n Proto. To solve this, you'll need to build Cap'n Proto from git master rather than the latest release. This admittedly goes against Cap'n Proto's own advice, where we usually tell people to stick to release versions, but... well, there is no "release version" of Sandstorm itself. :)

I'll add a note about this to the readme.

**Comment by kentonv** [comment]
Oops, I see the readme actually claimed 0.5.0 was sufficient, which was true at the time but became untrue as Sandstorm advanced. Sorry about that.

**Comment by seamus-oconnor** [comment]
Ahh make sense thanks @kentonv. But now I am getting this error:

```
$ make dev
capnp compile --src-prefix=/opt/sandstorm/latest/usr/include -oc++:tmp /opt/sandstorm/latest/usr/include/sandstorm/*.capnp
clang++ -static server.c++ tmp/sandstorm/*.capnp.c++ -o server -std=c++1y -Itmp -O2 -Wall `pkg-config capnp-rpc --cflags --libs`
Package capnp-rpc was not found in the pkg-config search path.
Perhaps you should add the directory containing `capnp-rpc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'capnp-rpc' found
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:23: recipe for target 'server' failed
make: *** [server] Error 1
```

That was after I followed the "From git" instructions on https://capnproto.org/install.html

```
git clone https://github.com/sandstorm-io/capnproto.git
cd capnproto/c++
./setup-autotools.sh
autoreconf -i
./configure
make -j6 check
sudo make install
```

However the `$ ./setup-autotools.sh` step produced this:

```
This script is no longer needed. Go ahead and run autoreconf. For example:
  autoreconf -i && ./configure && make -j6 check && sudo make install
```

But running `autoreconf -i && ./configure && make -j6 check && sudo make install` seemed to succeed.

**Comment by kentonv** [comment]
That error looks like it's because you haven't installed static versions of the standard libraries. Some distros don't include static libs with the dev tools by default. We need to build a static library here because we plan to place this binary inside a package where the dynamic libs won't be available.
